### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by RogerCreasy** [RogerCreasy/ChassisPHP#99]
The file does not completely reflect what we are doing. 
It needs to be updated.
Here are my initial thoughts:
Section - Pull Request Process
Could you reword this to better match a PHP PR workflow?
Right now, I am the only approver. Perhaps this point could be reworded to include that the PR will be merged after review. Some PR approvals may be delayed for an opportunity for the community to review. (just an idea)

**Comment by LiamBailey** [comment]
Hi 

I can do this - so I update the Pull Request part so that they know their pull request will be reviewed and approved before merging, with possible delays as you said. I could also go over the entire document and make improvements to flow and grammar etc - I used to be a writer before my dev career kicked off?

**Comment by RogerCreasy** [comment]
@LiamBailey All that you propose sounds great! I appreciate your willingness to help.

**Comment by RogerCreasy** [comment]
Completed with PR #107
